const store = require('./app/store');
const cakeActions = require('./features/cake/cakeSlice').cakeActions;
const icecreamActions = require('./features/icecream/iceCreamSlice').icecreamActions;
const fetchUsers = require('./features/user/userSlice').fetchUsers;

/*A console log to see the return of the cake Actions 
auto-generated by the cakeSlice
*/
// console.log(cakeActions.ordered());
// console.log(cakeActions.restocked(1));
// console.log(icecreamActions.ordered());
// console.log(icecreamActions.restocked(1));



//Initial state of store
console.log("initial state: ", store.getState());


//Subscription to state changes and new value of state is logged to console after every state change
const unsubscribe = store.subscribe(() => {
    console.log("updated state: ", store.getState());
});

//Some actions are dispatched and changes are logged to the console
store.dispatch(cakeActions.ordered())
store.dispatch(cakeActions.restocked(1));
store.dispatch(fetchUsers());
// unsubscribe();